env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
plugins:
  - jsdoc
  - vue
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  'import/no-extraneous-dependencies':
    - error
    - devDependencies:
        - 'src/client/**'
        - 'test/**'
        - 'tools/**'
      optionalDependencies: false
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allow:
        - '__GetDependency__'
        - '__Rewire__'
        - '__ResetDependency__'
        - '__get__'
        - '__set__'
  no-use-before-define:
    - error
    - functions: false
      classes: true
      variables: true
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  class-methods-use-this: off
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - e          # for e.returnvalue
        - req        # for Express requests
        - request    # for Express requests
        - res        # for Express responses
        - response   # for Express responses
        - t          # for Ava test
  'jsdoc/check-param-names': warn
  'jsdoc/check-tag-names': warn
  'jsdoc/check-types': warn
  'jsdoc/newline-after-description': warn
  'jsdoc/require-description-complete-sentence': off
  'jsdoc/require-hyphen-before-param-description': warn
  'jsdoc/require-param': warn
  'jsdoc/require-param-description': warn
  'jsdoc/require-param-type': warn
  'jsdoc/require-returns-description': warn
  'jsdoc/require-returns-type': warn
